config/routes.rb
Rails.application.routes.draw do
  resources :room_types
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :hotels do
    resources :rooms
  end
  resources :bookings
  devise_for :users

  root 'bookings#index'

end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :room
  validate :check_in_is_valid_datetime
  validate :check_out_is_valid_datetime

  def check_in_is_valid_datetime
    errors.add(:check_in, 'must be a valid datetime') if ((DateTime.parse(check_in.to_s) rescue ArgumentError) == ArgumentError)
  end

  def check_out_is_valid_datetime
    errors.add(:check_out, 'must be a valid datetime') if ((DateTime.parse(check_out.to_s) rescue ArgumentError) == ArgumentError)
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /bookings
  # GET /bookings.json
  def index
    @bookings = Booking.where(user_id: current_user.id)
  end

  # GET /bookings/1
  # GET /bookings/1.json
  def show
  end

  # GET /bookings/new
  def new
    @booking = Booking.new
  end

  # GET /bookings/1/edit
  def edit
  end

  # POST /bookings
  # POST /bookings.json
  def create
    @user = current_user
    @booking = Booking.new(booking_params)
    @booking.user = @user
    respond_to do |format|
      if @booking.save
        format.html { redirect_to @booking, notice: 'Booking was successfully created.' }
        format.json { render :show, status: :created, location: @booking }
      else
        format.html { render :new }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookings/1
  # PATCH/PUT /bookings/1.json
  def update
    respond_to do |format|
      if @booking.update(booking_params)
        format.html { redirect_to @booking, notice: 'Booking was successfully updated.' }
        format.json { render :show, status: :ok, location: @booking }
      else
        format.html { render :edit }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookings/1
  # DELETE /bookings/1.json
  def destroy
    @booking.destroy
    respond_to do |format|
      format.html { redirect_to bookings_url, notice: 'Booking was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_booking
    @booking = Booking.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def booking_params
    params.require(:booking).permit(:check_in, :check_out, :user_id, :room_id, :hotel_id)
  end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/_form.html.erb
<%= form_for @booking, :html => { :class => "form-horizontal room" } do |f| %>
  <% if @booking.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@booking.errors.count, "error") %> prohibited this booking from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @booking.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :check_in, class: 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :check_in, class: 'form-control' %>
    </div>
    <%=f.error_span(:check_in) %>
  </div>
  <div class="form-group">
    <%= f.label :check_out, class: 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :check_out, class: 'form-control' %>
    </div>
    <%=f.error_span(:check_out) %>
  </div>
  <%= f.hidden_field :user_id, class: 'form-control'%>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, class: 'btn btn-primary' %>
      <%= link_to t('.cancel', default: t("helpers.links.cancel")),
                bookings_path, class: 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/bookings/_index.html.erb
<%- model_class = Booking -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:check_in) %></th>
      <th><%= model_class.human_attribute_name(:check_out) %></th>
      <th><%= model_class.human_attribute_name(:room_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% bookings.each do |booking| %>
      <tr>
        <td><%= link_to booking.id, booking_path(booking) %></td>
        <td><%= booking.check_in %></td>
        <td><%= booking.check_out %></td>
        <td><%= booking.user_id %></td>
        <td><%= booking.room_id %></td>
        <td><%=l booking.created_at %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      booking_path(booking), :class => 'btn btn-default btn-xs' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            hotels_path,
            :class => 'btn btn-primary' %>

app/views/bookings/edit.html.erb
<%- model_class = Booking -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/bookings/index.html.erb
<%- model_class = Booking -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:check_in) %></th>

      <th><%= model_class.human_attribute_name(:check_out) %></th>
      <th><%= model_class.human_attribute_name(:user_id) %></th>
      <th><%= model_class.human_attribute_name(:room_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @bookings.each do |booking| %>
      <tr>
        <td><%= link_to booking.id, booking_path(booking) %></td>
        <td><%= booking.check_in %></td>
        <td><%= booking.check_out %></td>
        <td><%= booking.user_id %></td>
        <td><%= booking.room_id %></td>
        <td><%=l booking.created_at %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      booking_path(booking), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_booking_path(booking), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      booking_path(booking),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            hotels_path,
            :class => 'btn btn-primary' %>

app/views/bookings/new.html.erb
<%- model_class = Booking -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/bookings/show.html.erb
<%- model_class = Booking -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:check_in) %>:</strong></dt>
  <dd><%= @booking.check_in %></dd>
  <dt><strong><%= model_class.human_attribute_name(:check_out) %>:</strong></dt>
  <dd><%= @booking.check_out %></dd>
  <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><%= @booking.user_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:room_id) %>:</strong></dt>
  <dd><%= @booking.room_id %></dd>
</dl>
<%= link_to t('.back', :default => t("helpers.links.back")),
              bookings_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_booking_path(@booking), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              booking_path(@booking),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
<%= render '/bookings/form', booking: @booking, hotel: @room %>