config/routes.rb
Rails.application.routes.draw do
  resources :room_types
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :hotels do
    resources :rooms
  end
  resources :bookings
  devise_for :users

  root 'bookings#index'

end

app/controllers/room_types_controller.rb
class RoomTypesController < InheritedResources::Base

  private

    def room_type_params
      params.require(:room_type).permit(:name, :price)
    end
end

app/helpers/room_types_helper.rb
module RoomTypesHelper
end

app/views/room_types/_form.html.erb
<%= form_with(model: room_type, local: true) do |form| %>
  <% if room_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(room_type.errors.count, "error") %> prohibited this room_type from being saved:</h2>

      <ul>
      <% room_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :room_type_name %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price, id: :room_type_price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/room_types/edit.html.erb
<h1>Editing Room Type</h1>

<%= render 'form', room_type: @room_type %>

<%= link_to 'Show', @room_type %> |
<%= link_to 'Back', room_types_path %>

app/views/room_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Room Types</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @room_types.each do |room_type| %>
      <tr>
        <td><%= room_type.name %></td>
        <td><%= room_type.price %></td>
        <td><%= link_to 'Show', room_type %></td>
        <td><%= link_to 'Edit', edit_room_type_path(room_type) %></td>
        <td><%= link_to 'Destroy', room_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Room Type', new_room_type_path %>

app/views/room_types/new.html.erb
<h1>New Room Type</h1>

<%= render 'form', room_type: @room_type %>

<%= link_to 'Back', room_types_path %>

app/views/room_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @room_type.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @room_type.price %>
</p>

<%= link_to 'Edit', edit_room_type_path(@room_type) %> |
<%= link_to 'Back', room_types_path %>