config/routes.rb
Rails.application.routes.draw do
  resources :room_types
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :hotels do
    resources :rooms
  end
  resources :bookings
  devise_for :users

  root 'bookings#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "HotelTest" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>
    <div class="navbar navbar-default navbar-static-top">
      <div class="container">

        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>

        </button>
        <a class="navbar-brand" href="#">HotelTest</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to hotels_path  do %>
                  <%= t(:hotels) %>
                <% end %>
            </li>
            <li><%= link_to bookings_path  do %>
                  <%= t(:bookings) %>
                <% end %>
            </li>
            <li><%= link_to admin_users_path  do %>
                  <%= t(:admin) %>
                <% end %>
            </li>

              <% if user_signed_in? %>
                <li>
                  <%= link_to 'Edit profile', edit_user_registration_path %>
                </li>
                <li>
                  <%= link_to "Logout", destroy_user_session_path, method: :delete %>
                </li>
              <% else %>
              <li>
                <%= link_to "Sign up", new_user_registration_path %>
              </li>
              <li>
                <%= link_to "Login", new_user_session_path %>
                </li>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <% if user_signed_in? %>
            Logged in as <strong><%= current_user.email %></strong>.
            <% end %>
          <%= yield %>

        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Hotel Test 2017</p>
      </footer>


    </div> <!-- /container -->

  </body>
</html>